/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/dt/train_params": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Parameters
         * @description Gets the parameters for training.
         *
         *     Returns:
         *         List[ParameterInfo]: List of parameters for training
         */
        get: operations["get_parameters_api_dt_train_params_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dt/train": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Train Model
         * @description Train a decision tree model with the specified parameters.
         *
         *     Supports both predefined datasets (iris, wine, breast_cancer, digits)
         *     and custom datasets. Models are automatically cached for efficiency.
         *
         *     Args:
         *         request (DecisionTreeTrainingRequest): The request parameters
         *
         *     Raises:
         *         HTTPException: Exception if unable to train model
         *
         *     Returns:
         *         DecisionTreeTrainingResponse: Model details
         */
        post: operations["train_model_api_dt_train_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dt/predict_params": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Predict Params
         * @description Gets params for prediction
         *
         *     Args:
         *         request (DecisionTreeTrainingRequest): Request
         *
         *     Raises:
         *         HTTPException: Exception if retrieval failed
         *
         *     Returns:
         *         List[str]: Feature names
         */
        post: operations["get_predict_params_api_dt_predict_params_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dt/cache": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Clear Cache
         * @description Clear all cached models.
         */
        delete: operations["clear_cache_api_dt_cache_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dt/cache/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Cache Info
         * @description Get cache statistics and information.
         */
        get: operations["get_cache_info_api_dt_cache_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dataset/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Available Datasets
         * @description Get a list of all available predefined datasets.
         *
         *     Returns:
         *         DatasetListResponse: Dictionary of dataset names and their metadata
         */
        get: operations["get_available_datasets_api_dataset_list_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dataset/load": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Load Dataset
         * @description Load a dataset with its full data for visualization.
         *
         *     Defaults to the Iris dataset if no name is provided.
         *     Returns the complete dataset including feature values, labels,
         *     and metadata needed for visualization.
         *
         *     Args:
         *         name: Dataset name (defaults to "iris")
         *         test_size: Test set proportion (defaults to 0.25)
         *         random_state: Random seed (defaults to 2025)
         *
         *     Returns:
         *         DatasetResponse: Complete dataset with features, labels, and metadata
         *
         *     Raises:
         *         HTTPException: If dataset loading fails
         */
        get: operations["load_dataset_api_dataset_load_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knn/params": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Parameters
         * @description Get the parameters for KNN.
         *
         *     Returns:
         *         List[ParameterInfo]: List of parameters for KNN
         */
        get: operations["get_parameters_api_knn_params_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knn/predict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Predict
         * @description Make KNN predictions with visualization data.
         *
         *     KNN is a lazy learner - no training phase needed. This endpoint
         *     fits the model on the provided dataset and makes predictions
         *     for the query points, returning neighbor information and
         *     decision boundary data for visualization.
         *
         *     Args:
         *         request (KNNPredictionRequest): Prediction request with parameters,
         *             dataset, and query points
         *
         *     Raises:
         *         HTTPException: If prediction fails
         *
         *     Returns:
         *         KNNPredictionResponse: Predictions, neighbor info, and visualization data
         */
        post: operations["predict_api_knn_predict_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knn/visualise": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Visualise
         * @description Get KNN visualisation data without making predictions.
         *
         *     This endpoint is useful for visualising the training dataset
         *     with decision boundaries BEFORE making any predictions. It returns
         *     all training points and the decision boundary based on KNN parameters,
         *     but does not require any query points.
         *
         *     Use cases:
         *     - Initial dataset exploration
         *     - Understanding how K affects decision boundaries
         *     - Visualising feature spaces before prediction
         *
         *     Args:
         *         request (KNNVisualisationRequest): Visualisation request with parameters
         *             and dataset
         *
         *     Raises:
         *         HTTPException: If visualisation generation fails
         *
         *     Returns:
         *         KNNVisualisationResponse: Training data, decision boundary, and metadata
         */
        post: operations["visualise_api_knn_visualise_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnyParameterInfo
         * @description Any type parameter.
         */
        AnyParameterInfo: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Default */
            default: unknown;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "any";
        };
        /** BaseMetrics */
        BaseMetrics: {
            /** Accuracy */
            accuracy: number;
            /** Precision */
            precision: number;
            /** Recall */
            recall: number;
            /** F1 */
            f1: number;
        };
        /**
         * CacheInfoResponse
         * @description Response model for cache information.
         */
        CacheInfoResponse: {
            /** Enabled */
            enabled: boolean;
            /** Current Size */
            current_size: number;
            /** Max Size */
            max_size: number;
            /** Keys */
            keys: string[] | string;
        };
        /**
         * DatasetInfo
         * @description Metadata about a dataset.
         */
        DatasetInfo: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** N Samples */
            n_samples: number;
            /** N Features */
            n_features: number;
            /** N Classes */
            n_classes: number;
            /**
             * Target Type
             * @default classification
             * @enum {string}
             */
            target_type: "classification" | "regression";
        };
        /**
         * DatasetListResponse
         * @description Response model for available datasets.
         */
        DatasetListResponse: {
            /** Datasets */
            datasets: {
                [key: string]: components["schemas"]["DatasetInfo"];
            };
        };
        /**
         * DatasetResponse
         * @description Response model for loaded dataset.
         */
        DatasetResponse: {
            /** Success */
            success: boolean;
            /**
             * X
             * @description Feature matrix
             */
            X: number[][];
            /**
             * Y
             * @description Target vector
             */
            y: number[];
            /**
             * Feature Names
             * @description Names of features
             */
            feature_names: string[];
            /**
             * Target Names
             * @description Names of target classes
             */
            target_names: string[];
            /** @description Dataset metadata */
            info: components["schemas"]["DatasetInfo"];
            /**
             * Test Size
             * @description Test set proportion
             */
            test_size: number;
            /**
             * Random State
             * @description Random seed for reproducibility
             */
            random_state: number;
        };
        /**
         * DecisionBoundaryData
         * @description Decision boundary visualization data.
         */
        DecisionBoundaryData: {
            /**
             * Mesh Points
             * @description Grid points for boundary visualization
             */
            mesh_points: number[][];
            /**
             * Predictions
             * @description Predicted class at each mesh point
             */
            predictions: string[];
            /**
             * Dimensions
             * @description Number of dimensions (1, 2, or 3)
             */
            dimensions: number;
        };
        /**
         * DecisionTreeTrainingRequest
         * @description Request model for Decision Tree.
         */
        DecisionTreeTrainingRequest: {
            /**
             * Max Depth
             * @description Maximum depth of the tree
             * @default 5
             */
            max_depth: number | null;
            /**
             * Criterion
             * @description Split quality criterion
             * @default gini
             * @enum {string}
             */
            criterion: "gini" | "entropy";
            /**
             * Min Samples Split
             * @description Minimum samples to split
             * @default 2
             */
            min_samples_split: number | null;
            /**
             * Min Samples Leaf
             * @description Minimum samples at leaf
             * @default 1
             */
            min_samples_leaf: number | null;
            /**
             * Max Features
             * @description Number of features to consider
             */
            max_features?: ("sqrt" | "log2") | null;
            /**
             * Random State
             * @description Random seed for reproducibility
             * @default 2025
             */
            random_state: number | null;
            /**
             * Dataset
             * @description Dataset to use for training
             */
            dataset?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * DecisionTreeTrainingResponse
         * @description Response model for Decision Tree.
         */
        DecisionTreeTrainingResponse: {
            /** Success */
            success: boolean;
            /** Model Key */
            model_key: string;
            /** Cached */
            cached: boolean;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            tree: components["schemas"]["TreeNode"];
            /** Classes */
            classes: string[];
            /** Matrix */
            matrix: number[][];
            scores: components["schemas"]["BaseMetrics"];
        };
        /**
         * FloatParameterInfo
         * @description Float parameter with optional range and step.
         */
        FloatParameterInfo: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Default */
            default: unknown;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "float";
            /** Min */
            min?: number | null;
            /** Max */
            max?: number | null;
            /** Step */
            step?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistogramData */
        HistogramData: {
            /** Feature Values */
            feature_values: number[];
            /** Class Labels */
            class_labels: number[];
            /** Bins */
            bins: number[];
            /** Counts By Class */
            counts_by_class: {
                [key: string]: number[];
            };
            /** Threshold */
            threshold: number | null;
            /** Total Samples */
            total_samples: number;
        };
        /**
         * IntParameterInfo
         * @description Integer parameter with optional range.
         */
        IntParameterInfo: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Default */
            default: unknown;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "int";
            /** Min */
            min?: number | null;
            /** Max */
            max?: number | null;
        };
        /**
         * KNNParameters
         * @description Core KNN algorithm parameters matching sklearn.neighbors.KNeighborsClassifier.
         */
        KNNParameters: {
            /**
             * N Neighbors
             * @description Number of neighbors to use
             * @default 5
             */
            n_neighbors: number;
            /**
             * Weights
             * @description Weight function: 'uniform' (equal weights) or 'distance' (inverse distance weighting)
             * @default uniform
             * @enum {string}
             */
            weights: "uniform" | "distance";
            /**
             * Algorithm
             * @description Algorithm to compute nearest neighbors
             * @default auto
             * @enum {string}
             */
            algorithm: "auto" | "ball_tree" | "kd_tree" | "brute";
            /**
             * Leaf Size
             * @description Leaf size passed to BallTree or KDTree (affects speed and memory)
             * @default 30
             */
            leaf_size: number;
            /**
             * P
             * @description Power parameter for Minkowski metric (p=1: Manhattan, p=2: Euclidean)
             * @default 2
             */
            p: number;
            /**
             * Metric
             * @description Distance metric to use
             * @default minkowski
             * @enum {string}
             */
            metric: "minkowski" | "euclidean" | "manhattan" | "chebyshev";
        };
        /**
         * KNNPredictionRequest
         * @description Request model for KNN prediction.
         */
        KNNPredictionRequest: {
            /** @description KNN algorithm parameters (defaults to n_neighbors=5, uniform weights, etc.) */
            parameters?: components["schemas"]["KNNParameters"];
            /**
             * Dataset
             * @description Training dataset with X, y, feature_names, class_names. Defaults to Iris dataset.
             */
            dataset?: {
                [key: string]: unknown;
            } | null;
            /**
             * Query Points
             * @description Test points to classify
             */
            query_points: number[][];
            /**
             * Visualisation Features
             * @description Indices for visualisation features
             */
            visualisation_features?: number[] | null;
            /**
             * Include Boundary
             * @description Whether to include decision boundary data
             * @default true
             */
            include_boundary: boolean;
            /**
             * Boundary Resolution
             * @description Resolution of boundary mesh
             * @default 50
             */
            boundary_resolution: number;
        };
        /**
         * KNNPredictionResponse
         * @description Response model for KNN prediction.
         */
        KNNPredictionResponse: {
            /** Success */
            success: boolean;
            /**
             * Predictions
             * @description Predicted class labels
             */
            predictions: string[];
            /**
             * Prediction Indices
             * @description Predicted class indices
             */
            prediction_indices: number[];
            /**
             * Neighbors Info
             * @description Neighbor information for each query point
             */
            neighbors_info: components["schemas"]["NeighborInfo"][][];
            /**
             * Training Points
             * @description All training point coordinates
             */
            training_points: number[][];
            /**
             * Training Labels
             * @description All training point labels
             */
            training_labels: string[];
            /**
             * All Distances
             * @description Distance from each query point to all training points
             */
            all_distances: number[][];
            /**
             * Distance Matrix
             * @description Distance from each training point to all other training points (0 for self)
             */
            distance_matrix: number[][];
            /**
             * Neighbor Indices
             * @description Indices of K nearest neighbors for each training point (sorted by distance)
             */
            neighbor_indices: number[][];
            /** @description Decision boundary visualization data */
            decision_boundary?: components["schemas"]["DecisionBoundaryData"] | null;
            /** Feature Names */
            feature_names: string[];
            /** Class Names */
            class_names: string[];
            /** N Dimensions */
            n_dimensions: number;
        };
        /**
         * KNNVisualisationRequest
         * @description Request model for KNN visualisation without prediction.
         */
        KNNVisualisationRequest: {
            /** @description KNN algorithm parameters */
            parameters?: components["schemas"]["KNNParameters"];
            /**
             * Dataset
             * @description Training dataset. Defaults to Iris dataset.
             */
            dataset?: {
                [key: string]: unknown;
            } | null;
            /**
             * Visualisation Features
             * @description Feature indices to visualise (1-3 features)
             */
            visualisation_features?: number[] | null;
            /**
             * Include Boundary
             * @description Whether to include decision boundary
             * @default true
             */
            include_boundary: boolean;
            /**
             * Boundary Resolution
             * @description Resolution of boundary mesh
             * @default 50
             */
            boundary_resolution: number;
        };
        /**
         * KNNVisualisationResponse
         * @description Response model for KNN visualisation without prediction.
         */
        KNNVisualisationResponse: {
            /** Success */
            success: boolean;
            /**
             * Training Points
             * @description All training point coordinates (visualisation features only)
             */
            training_points: number[][];
            /**
             * Training Labels
             * @description All training point labels
             */
            training_labels: string[];
            /**
             * Distance Matrix
             * @description Distance from each training point to all other training points (0 for self)
             */
            distance_matrix: number[][];
            /**
             * Neighbor Indices
             * @description Indices of K nearest neighbors for each training point (sorted by distance)
             */
            neighbor_indices: number[][];
            /** @description Decision boundary visualisation data */
            decision_boundary?: components["schemas"]["DecisionBoundaryData"] | null;
            /** Feature Names */
            feature_names: string[];
            /** Class Names */
            class_names: string[];
            /** N Dimensions */
            n_dimensions: number;
            /**
             * Visualisation Feature Indices
             * @description Feature indices used for visualisation
             */
            visualisation_feature_indices?: number[] | null;
            /**
             * Visualisation Feature Names
             * @description Names of features used for visualisation
             */
            visualisation_feature_names?: string[] | null;
        };
        /**
         * NeighborInfo
         * @description Information about a single neighbor.
         */
        NeighborInfo: {
            /**
             * Index
             * @description Index in training data
             */
            index: number;
            /**
             * Distance
             * @description Distance from query point
             */
            distance: number;
            /**
             * Label
             * @description Class label
             */
            label: string;
            /**
             * Coordinates
             * @description Feature values
             */
            coordinates: number[];
        };
        /**
         * NumberParameterInfo
         * @description Number parameter with optional range and step.
         */
        NumberParameterInfo: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Default */
            default: unknown;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "number";
            /** Min */
            min?: number | null;
            /** Max */
            max?: number | null;
            /** Step */
            step?: number | null;
        };
        /**
         * SelectParameterInfo
         * @description Select parameter with predefined options.
         */
        SelectParameterInfo: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Default */
            default: unknown;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "select";
            /** Options */
            options: unknown[];
        };
        /**
         * TreeNode
         * @description Core domain model for decision tree nodes.
         */
        TreeNode: {
            /**
             * Type
             * @enum {string}
             */
            type: "split" | "leaf";
            /** Samples */
            samples: number;
            /** Impurity */
            impurity: number;
            /** Value */
            value: number[][];
            /** Feature */
            feature?: string | null;
            /** Feature Index */
            feature_index?: number | null;
            /** Threshold */
            threshold?: number | null;
            histogram_data?: components["schemas"]["HistogramData"] | null;
            left?: components["schemas"]["TreeNode"] | null;
            right?: components["schemas"]["TreeNode"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_parameters_api_dt_train_params_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": (components["schemas"]["SelectParameterInfo"] | components["schemas"]["IntParameterInfo"] | components["schemas"]["NumberParameterInfo"] | components["schemas"]["FloatParameterInfo"] | components["schemas"]["AnyParameterInfo"])[];
                };
            };
        };
    };
    train_model_api_dt_train_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionTreeTrainingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionTreeTrainingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_predict_params_api_dt_predict_params_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionTreeTrainingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_cache_api_dt_cache_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_cache_info_api_dt_cache_info_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CacheInfoResponse"];
                };
            };
        };
    };
    get_available_datasets_api_dataset_list_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetListResponse"];
                };
            };
        };
    };
    load_dataset_api_dataset_load_get: {
        parameters: {
            query?: {
                /** @description Dataset name (iris, wine, breast_cancer, digits) */
                name?: string | null;
                /** @description Proportion of dataset to use for test split */
                test_size?: number | null;
                /** @description Random seed for train/test split */
                random_state?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_parameters_api_knn_params_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": (components["schemas"]["SelectParameterInfo"] | components["schemas"]["IntParameterInfo"] | components["schemas"]["NumberParameterInfo"] | components["schemas"]["FloatParameterInfo"] | components["schemas"]["AnyParameterInfo"])[];
                };
            };
        };
    };
    predict_api_knn_predict_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KNNPredictionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KNNPredictionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    visualise_api_knn_visualise_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KNNVisualisationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KNNVisualisationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
